use_frameworks!

platform :ios, '9.0'

target 'MOZITools_Example' do
  pod 'MOZITools', :path => '../'

  target 'MOZITools_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
